name: "TwinSync Spot"
description: "Does this match YOUR definition? Compare camera snapshots to YOUR description of how a space should look."
version: "1.0.4"
slug: "twinsync_spot"
url: "https://github.com/kozzzzzzy/twin-sync-addon-final"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 8099
panel_icon: "mdi:map-marker-check"
panel_title: "TwinSync Spot"
startup: application
boot: auto
init: false
options:
  gemini_api_key: ""
schema:
  gemini_api_key: str
ports:
  8099/tcp: null
map:
  - addon_config:rw
